global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090
- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
    - 10.94.1.129:9100
    - 10.94.1.131:9100
- job_name: proxmox-servers
  static_configs:
  - targets: []
- job_name: proxmox-manager
  static_configs:
  - targets:
    - host.docker.internal:5000
  metrics_path: /metrics
  scrape_interval: 30s
